# Setting Units
# Setting Factors(will create new variable for factors)

data$redcap_event_name <- factor(data$redcap_event_name, levels = c("day_1_hospital_adm_arm_1", "day_3_arm_1", "day_6_arm_1", "day_9_arm_1", "additional_days_arm_1", "dischargedeath_arm_1", "day_1_hospitalicu_arm_2", "day_3_arm_2", "day_6_arm_2", "day_9_arm_2", "additional_days_arm_2", "dischargedeath_arm_2", "day_1_arm_3", "day_2_arm_3", "day_3_arm_3", "day_4_arm_3", "day_5_arm_3", "day_6_arm_3", "day_7_arm_3", "day_8_arm_3", "day_9_arm_3", "day_10_arm_3", "day_11_arm_3", "day_12_arm_3", "day_13_arm_3", "day_14_arm_3", "additional_days_arm_3", "dischargedeath_arm_3"))
data$redcap_repeat_instrument <- factor(data$redcap_repeat_instrument, levels = c("preadmission_medication", "infectious_respiratory_disease_pathogen_testing", "daily_form"))
data$participant_identification_number_pin_complete <- factor(data$participant_identification_number_pin_complete, levels = c("0", "1", "2"))
data$tiers_faorres___1 <- factor(data$tiers_faorres___1, levels = c("0", "1"))
data$tiers_faorres___2 <- factor(data$tiers_faorres___2, levels = c("0", "1"))
data$tiers_faorres___3 <- factor(data$tiers_faorres___3, levels = c("0", "1"))
data$tiers_consent_complete <- factor(data$tiers_consent_complete, levels = c("0", "1", "2"))
data$corona_ieorres <- factor(data$corona_ieorres, levels = c("1", "0"))
data$coriona_ieorres2 <- factor(data$coriona_ieorres2, levels = c("1", "0"))
data$fever <- factor(data$fever, levels = c("1", "0"))
data$cough <- factor(data$cough, levels = c("1", "0"))
data$dyspnoe <- factor(data$dyspnoe, levels = c("1", "0"))
data$ari <- factor(data$ari, levels = c("1", "0"))
data$symptoms_epi_travel <- factor(data$symptoms_epi_travel, levels = c("1", "2", "3"))
data$symptoms_epi_physical <- factor(data$symptoms_epi_physical, levels = c("1", "2", "3"))
data$symptoms_epi_healthfac <- factor(data$symptoms_epi_healthfac, levels = c("1", "2", "3"))
data$symptoms_epi_lab <- factor(data$symptoms_epi_lab, levels = c("1", "2", "3"))
data$symptoms_epi_pathogen <- factor(data$symptoms_epi_pathogen, levels = c("1", "2", "3"))
data$symptoms_epi_animal <- factor(data$symptoms_epi_animal, levels = c("1", "2", "3"))
data$inclusion_criteria_complete <- factor(data$inclusion_criteria_complete, levels = c("0", "1", "2"))
data$sex <- factor(data$sex, levels = c("1", "2", "3"))
data$agedatyn <- factor(data$agedatyn, levels = c("1", "0"))
data$age_estimateyearsu <- factor(data$age_estimateyearsu, levels = c("1", "2"))
data$ethnic___1 <- factor(data$ethnic___1, levels = c("0", "1"))
data$ethnic___2 <- factor(data$ethnic___2, levels = c("0", "1"))
data$ethnic___3 <- factor(data$ethnic___3, levels = c("0", "1"))
data$ethnic___4 <- factor(data$ethnic___4, levels = c("0", "1"))
data$ethnic___5 <- factor(data$ethnic___5, levels = c("0", "1"))
data$ethnic___6 <- factor(data$ethnic___6, levels = c("0", "1"))
data$ethnic___7 <- factor(data$ethnic___7, levels = c("0", "1"))
data$ethnic___8 <- factor(data$ethnic___8, levels = c("0", "1"))
data$ethnic___9 <- factor(data$ethnic___9, levels = c("0", "1"))
data$ethnic___10 <- factor(data$ethnic___10, levels = c("0", "1"))
data$healthwork_erterm <- factor(data$healthwork_erterm, levels = c("1", "2", "3"))
data$labwork_erterm <- factor(data$labwork_erterm, levels = c("1", "2", "3"))
data$pregyn_rptestcd <- factor(data$pregyn_rptestcd, levels = c("1", "0", "998", "999"))
data$postpart_rptestcd <- factor(data$postpart_rptestcd, levels = c("1", "0"))
data$pregout_rptestcd <- factor(data$pregout_rptestcd, levels = c("1", "2"))
data$aplb_lbperf <- factor(data$aplb_lbperf, levels = c("1", "2", "3"))
data$aplb_lborres <- factor(data$aplb_lborres, levels = c("1", "2"))
data$aplb_lbmethod <- factor(data$aplb_lbmethod, levels = c("1", "2"))
data$apdm_age <- factor(data$apdm_age, levels = c("1", "0"))
data$apvs_weightu <- factor(data$apvs_weightu, levels = c("1", "2"))
data$apsc_gestout <- factor(data$apsc_gestout, levels = c("1", "2", "3"))
data$apsc_brfedind <- factor(data$apsc_brfedind, levels = c("1", "2", "3"))
data$apsc_brfedindy <- factor(data$apsc_brfedindy, levels = c("1", "2", "3"))
data$apsc_dvageind <- factor(data$apsc_dvageind, levels = c("1", "2", "3"))
data$apsc_vcageind <- factor(data$apsc_vcageind, levels = c("1", "2", "3", "4"))
data$demographics_complete <- factor(data$demographics_complete, levels = c("0", "1", "2"))
data$hooccur <- factor(data$hooccur, levels = c("1", "2", "3", "4"))
data$subjidcat_transfer <- factor(data$subjidcat_transfer, levels = c("1", "2", "3"))
data$travel_erterm <- factor(data$travel_erterm, levels = c("1", "2", "3"))
data$supper_trcntry <- factor(data$supper_trcntry, levels = c("4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "Bahamas", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "Congo", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "Gambia", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "Korea", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200"))
data$travel_erterm_2 <- factor(data$travel_erterm_2, levels = c("1", "2", "3"))
data$supper_trcntry_2 <- factor(data$supper_trcntry_2, levels = c("4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "Bahamas", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "Congo", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "Gambia", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "Korea", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200"))
data$animal_eryn <- factor(data$animal_eryn, levels = c("1", "2", "3", "4"))
data$animal_eryn_2 <- factor(data$animal_eryn_2, levels = c("1", "2", "3", "4"))
data$onset_and_admission_complete <- factor(data$onset_and_admission_complete, levels = c("0", "1", "2"))
data$temp_vsyn <- factor(data$temp_vsyn, levels = c("1", "0"))
data$temp_vsorresu <- factor(data$temp_vsorresu, levels = c("1", "2"))
data$hr_vsyn <- factor(data$hr_vsyn, levels = c("1", "0"))
data$rr_vsyn <- factor(data$rr_vsyn, levels = c("1", "0"))
data$sysbp_vsyn <- factor(data$sysbp_vsyn, levels = c("1", "0"))
data$diabp_vsyn <- factor(data$diabp_vsyn, levels = c("1", "0"))
data$dehydration_vsorres <- factor(data$dehydration_vsorres, levels = c("1", "2", "3"))
data$stercap_vsyn <- factor(data$stercap_vsyn, levels = c("1", "0"))
data$stercap_vsorres <- factor(data$stercap_vsorres, levels = c("1", "2", "3"))
data$oxy_vsyn <- factor(data$oxy_vsyn, levels = c("1", "0"))
data$oxy_vsorresu <- factor(data$oxy_vsorresu, levels = c("1", "2", "3"))
data$fever_ceoccur_v2 <- factor(data$fever_ceoccur_v2, levels = c("1", "2", "3"))
data$cough_ceoccur_v2 <- factor(data$cough_ceoccur_v2, levels = c("1", "2", "3"))
data$coughsput_ceoccur_v2 <- factor(data$coughsput_ceoccur_v2, levels = c("1", "2", "3"))
data$coughhb_ceoccur_v2 <- factor(data$coughhb_ceoccur_v2, levels = c("1", "2", "3"))
data$sorethroat_ceoccur_v2 <- factor(data$sorethroat_ceoccur_v2, levels = c("1", "2", "3"))
data$runnynose_ceoccur_v2 <- factor(data$runnynose_ceoccur_v2, levels = c("1", "2", "3"))
data$earpain_ceoccur_v2 <- factor(data$earpain_ceoccur_v2, levels = c("1", "2", "3"))
data$wheeze_ceoccur_v2 <- factor(data$wheeze_ceoccur_v2, levels = c("1", "2", "3"))
data$chestpain_ceoccur_v2 <- factor(data$chestpain_ceoccur_v2, levels = c("1", "2", "3"))
data$myalgia_ceoccur_v2 <- factor(data$myalgia_ceoccur_v2, levels = c("1", "2", "3"))
data$jointpain_ceoccur_v2 <- factor(data$jointpain_ceoccur_v2, levels = c("1", "2", "3"))
data$fatigue_ceoccur_v2 <- factor(data$fatigue_ceoccur_v2, levels = c("1", "2", "3"))
data$shortbreath_ceoccur_v2 <- factor(data$shortbreath_ceoccur_v2, levels = c("1", "2", "3"))
data$lowerchest_ceoccur_v2 <- factor(data$lowerchest_ceoccur_v2, levels = c("1", "2", "3"))
data$headache_ceoccur_v2 <- factor(data$headache_ceoccur_v2, levels = c("1", "2", "3"))
data$confusion_ceoccur_v2 <- factor(data$confusion_ceoccur_v2, levels = c("1", "2", "3"))
data$seizures_cecoccur_v2 <- factor(data$seizures_cecoccur_v2, levels = c("1", "2", "3"))
data$abdopain_ceoccur_v2 <- factor(data$abdopain_ceoccur_v2, levels = c("1", "2", "3"))
data$vomit_ceoccur_v2 <- factor(data$vomit_ceoccur_v2, levels = c("1", "2", "3"))
data$diarrhoea_ceoccur_v2 <- factor(data$diarrhoea_ceoccur_v2, levels = c("1", "2", "3"))
data$conjunct_ceoccur_v2 <- factor(data$conjunct_ceoccur_v2, levels = c("1", "2", "3"))
data$rash_ceoccur_v2 <- factor(data$rash_ceoccur_v2, levels = c("1", "2", "3"))
data$skinulcers_ceoccur_v2 <- factor(data$skinulcers_ceoccur_v2, levels = c("1", "2", "3"))
data$lymp_ceoccur_v2 <- factor(data$lymp_ceoccur_v2, levels = c("1", "2", "3"))
data$bleed_ceoccur_v2 <- factor(data$bleed_ceoccur_v2, levels = c("1", "2", "3"))
data$bleed_ceterm_v2 <- factor(data$bleed_ceterm_v2, levels = c("1", "2", "3"))
data$admission_signs_and_symptoms_complete <- factor(data$admission_signs_and_symptoms_complete, levels = c("0", "1", "2"))
data$chrincard <- factor(data$chrincard, levels = c("1", "2", "3"))
data$chronicpul_mhyn <- factor(data$chronicpul_mhyn, levels = c("1", "2", "3"))
data$asthma_mhyn <- factor(data$asthma_mhyn, levels = c("1", "0", "2"))
data$renal_mhyn <- factor(data$renal_mhyn, levels = c("1", "2", "3"))
data$modliv <- factor(data$modliv, levels = c("1", "0", "2"))
data$mildliver <- factor(data$mildliver, levels = c("1", "0", "2"))
data$chronicneu_mhyn <- factor(data$chronicneu_mhyn, levels = c("1", "2", "3"))
data$malignantneo_mhyn <- factor(data$malignantneo_mhyn, levels = c("1", "2", "3"))
data$chronichaemo_mhyn <- factor(data$chronichaemo_mhyn, levels = c("1", "2", "3"))
data$aidshiv_mhyn <- factor(data$aidshiv_mhyn, levels = c("1", "2", "3"))
data$obesity_mhyn <- factor(data$obesity_mhyn, levels = c("1", "2", "3"))
data$diabetescom_mhyn <- factor(data$diabetescom_mhyn, levels = c("1", "2", "3"))
data$diabetes_mhyn <- factor(data$diabetes_mhyn, levels = c("1", "2", "3"))
data$rheumatologic_mhyn <- factor(data$rheumatologic_mhyn, levels = c("1", "2", "3"))
data$dementia_mhyn <- factor(data$dementia_mhyn, levels = c("1", "2", "3"))
data$malnutrition_mhyn <- factor(data$malnutrition_mhyn, levels = c("1", "2", "3"))
data$smoking_mhyn <- factor(data$smoking_mhyn, levels = c("1", "2", "3"))
data$other_mhyn <- factor(data$other_mhyn, levels = c("1", "2", "3"))
data$comorbidities_complete <- factor(data$comorbidities_complete, levels = c("0", "1", "2"))
data$immno_cmtrt <- factor(data$immno_cmtrt, levels = c("1", "2", "3"))
data$infect_cmtrt <- factor(data$infect_cmtrt, levels = c("1", "2", "3"))
data$preadmission_treatment_complete <- factor(data$preadmission_treatment_complete, levels = c("0", "1", "2"))
data$cmdosfrq <- factor(data$cmdosfrq, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"))
data$cmroute <- factor(data$cmroute, levels = c("1", "2", "3", "4", "5"))
data$preadmission_medication_complete <- factor(data$preadmission_medication_complete, levels = c("0", "1", "2"))
data$daily_hoterm <- factor(data$daily_hoterm, levels = c("1", "2", "3"))
data$daily_fi02_lbyn <- factor(data$daily_fi02_lbyn, levels = c("1", "2"))
data$daily_sa02_lbyn <- factor(data$daily_sa02_lbyn, levels = c("1", "2"))
data$daily_pao2_lbyn <- factor(data$daily_pao2_lbyn, levels = c("1", "0"))
data$daily_pao2_lborresu <- factor(data$daily_pao2_lborresu, levels = c("1", "2"))
data$daily_pao2_lbspec <- factor(data$daily_pao2_lbspec, levels = c("1", "2", "3", "4"))
data$daily_pco2_lbyn <- factor(data$daily_pco2_lbyn, levels = c("1", "2"))
data$daily_pco2_lborresu <- factor(data$daily_pco2_lborresu, levels = c("1", "2"))
data$daily_ph_lbyn <- factor(data$daily_ph_lbyn, levels = c("1", "0"))
data$daily_hco3_lbyn <- factor(data$daily_hco3_lbyn, levels = c("1", "0"))
data$daily_baseex_lbyn <- factor(data$daily_baseex_lbyn, levels = c("1", "0"))
data$avpu_vsorres <- factor(data$avpu_vsorres, levels = c("1", "2", "3", "4"))
data$daily_gcs_lbyn <- factor(data$daily_gcs_lbyn, levels = c("1", "0"))
data$systolic_vsyn <- factor(data$systolic_vsyn, levels = c("1", "0"))
data$diastolic_vsyn <- factor(data$diastolic_vsyn, levels = c("1", "0"))
data$daily_meanart_lbyn <- factor(data$daily_meanart_lbyn, levels = c("1", "0"))
data$daily_urine_lbyn <- factor(data$daily_urine_lbyn, levels = c("1", "2", "0"))
data$daily_noninvasive_prtrt <- factor(data$daily_noninvasive_prtrt, levels = c("1", "2", "3"))
data$daily_invasive_prtrt <- factor(data$daily_invasive_prtrt, levels = c("1", "2", "3"))
data$daily_nasaloxy_cmtrt <- factor(data$daily_nasaloxy_cmtrt, levels = c("1", "2", "3"))
data$daily_ecmo_prtrt <- factor(data$daily_ecmo_prtrt, levels = c("1", "2", "3"))
data$daily_rrt_cmtrt <- factor(data$daily_rrt_cmtrt, levels = c("1", "2", "3"))
data$daily_inotrope_cmyn <- factor(data$daily_inotrope_cmyn, levels = c("1", "2", "3"))
data$daily_dopless5_cmtrt <- factor(data$daily_dopless5_cmtrt, levels = c("1", "2", "3"))
data$daily_dop5to15_cmtrt <- factor(data$daily_dop5to15_cmtrt, levels = c("1", "2", "3"))
data$daily_dopgr15_cmtrt <- factor(data$daily_dopgr15_cmtrt, levels = c("1", "2", "3"))
data$daily_neuro_cmtrt <- factor(data$daily_neuro_cmtrt, levels = c("1", "2", "3"))
data$daily_nitritc_cmtrt <- factor(data$daily_nitritc_cmtrt, levels = c("1", "2", "3"))
data$daily_prone_cmtrt <- factor(data$daily_prone_cmtrt, levels = c("1", "2", "3"))
data$daily_trach_prperf <- factor(data$daily_trach_prperf, levels = c("1", "2", "3"))
data$daily_prperf <- factor(data$daily_prperf, levels = c("1", "2", "3"))
data$daily_lbperf <- factor(data$daily_lbperf, levels = c("1", "0"))
data$daily_hb_lbyn <- factor(data$daily_hb_lbyn, levels = c("1", "0"))
data$daily_hb_lborresu <- factor(data$daily_hb_lborresu, levels = c("1", "2"))
data$daily_wbc_lbyn <- factor(data$daily_wbc_lbyn, levels = c("1", "0"))
data$daily_wbc_lborresu <- factor(data$daily_wbc_lborresu, levels = c("1", "2"))
data$daily_lymp_lbyn <- factor(data$daily_lymp_lbyn, levels = c("1", "0"))
data$daily_neutro_lbyn <- factor(data$daily_neutro_lbyn, levels = c("1", "0"))
data$daily_haematocrit_lbyn <- factor(data$daily_haematocrit_lbyn, levels = c("1", "0"))
data$daily_plt_lbyn <- factor(data$daily_plt_lbyn, levels = c("1", "0"))
data$daily_plt_lborresu <- factor(data$daily_plt_lborresu, levels = c("1", "2"))
data$daily_aptt_lbyn <- factor(data$daily_aptt_lbyn, levels = c("1", "0"))
data$daily_pt_inr_lbyn <- factor(data$daily_pt_inr_lbyn, levels = c("1", "2", "3"))
data$daily_alt_lbyn <- factor(data$daily_alt_lbyn, levels = c("1", "0"))
data$daily_bil_lbyn <- factor(data$daily_bil_lbyn, levels = c("1", "0"))
data$daily_bil_lborresu <- factor(data$daily_bil_lborresu, levels = c("1", "2"))
data$daily_ast_lbyn <- factor(data$daily_ast_lbyn, levels = c("1", "0"))
data$daily_glucose_lbyn <- factor(data$daily_glucose_lbyn, levels = c("1", "0"))
data$daily_glucose_lborresu <- factor(data$daily_glucose_lborresu, levels = c("1", "2"))
data$daily_bun_lbyn <- factor(data$daily_bun_lbyn, levels = c("1", "0"))
data$daily_bun_lborresu <- factor(data$daily_bun_lborresu, levels = c("1", "2"))
data$daily_lactate_lbyn <- factor(data$daily_lactate_lbyn, levels = c("1", "0"))
data$daily_lactate_lborresu <- factor(data$daily_lactate_lborresu, levels = c("1", "2"))
data$daily_ldh_lbyn <- factor(data$daily_ldh_lbyn, levels = c("1", "0"))
data$daily_cpk_lby <- factor(data$daily_cpk_lby, levels = c("1", "0"))
data$daily_creat_lbyn <- factor(data$daily_creat_lbyn, levels = c("1", "0"))
data$daily_creat_lborresu <- factor(data$daily_creat_lborresu, levels = c("1", "2", "3"))
data$daily_sodium_lbyn <- factor(data$daily_sodium_lbyn, levels = c("1", "0"))
data$daily_potassium_lbyn <- factor(data$daily_potassium_lbyn, levels = c("1", "0"))
data$daily_procal_lbyn <- factor(data$daily_procal_lbyn, levels = c("1", "0"))
data$daily_crp_lbyn <- factor(data$daily_crp_lbyn, levels = c("1", "0"))
data$xray_prperf <- factor(data$xray_prperf, levels = c("1", "2", "3"))
data$infiltrates_faorres <- factor(data$infiltrates_faorres, levels = c("1", "2", "3"))
data$daily_form_complete <- factor(data$daily_form_complete, levels = c("0", "1", "2"))
data$mbperf <- factor(data$mbperf, levels = c("1", "2", "3"))
data$influ_mbyn <- factor(data$influ_mbyn, levels = c("2", "1", "0"))
data$influ_mbcat <- factor(data$influ_mbcat, levels = c("1", "2", "3", "4", "5", "6", "888"))
data$corna_mbcat <- factor(data$corna_mbcat, levels = c("2", "1", "0"))
data$corna_mbcaty <- factor(data$corna_mbcaty, levels = c("1", "2", "888"))
data$rsv_mbcat <- factor(data$rsv_mbcat, levels = c("2", "1", "0"))
data$adeno_mbcat <- factor(data$adeno_mbcat, levels = c("2", "1", "0"))
data$bact_mborres <- factor(data$bact_mborres, levels = c("1", "2"))
data$other_mbyn <- factor(data$other_mbyn, levels = c("2", "1", "0"))
data$clinicalpneu_mborres <- factor(data$clinicalpneu_mborres, levels = c("1", "0", "2"))
data$infectuk_mborres <- factor(data$infectuk_mborres, levels = c("1", "2"))
data$infectious_respiratory_disease_pathogen_diagnosis_complete <- factor(data$infectious_respiratory_disease_pathogen_diagnosis_complete, levels = c("0", "1", "2"))
data$daily_mbperf <- factor(data$daily_mbperf, levels = c("1", "0"))
data$mbspec <- factor(data$mbspec, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"))
data$mbmethod <- factor(data$mbmethod, levels = c("1", "2", "3"))
data$mborres <- factor(data$mborres, levels = c("1", "2", "3"))
data$infectious_respiratory_disease_pathogen_testing_complete <- factor(data$infectious_respiratory_disease_pathogen_testing_complete, levels = c("0", "1", "2"))
data$antiviral_cmyn <- factor(data$antiviral_cmyn, levels = c("1", "2", "3"))
data$antiviral_cmtrt___1 <- factor(data$antiviral_cmtrt___1, levels = c("0", "1"))
data$antiviral_cmtrt___2 <- factor(data$antiviral_cmtrt___2, levels = c("0", "1"))
data$antiviral_cmtrt___3 <- factor(data$antiviral_cmtrt___3, levels = c("0", "1"))
data$antiviral_cmtrt___4 <- factor(data$antiviral_cmtrt___4, levels = c("0", "1"))
data$antiviral_cmtrt___5 <- factor(data$antiviral_cmtrt___5, levels = c("0", "1"))
data$antiviral_cmtrt___6 <- factor(data$antiviral_cmtrt___6, levels = c("0", "1"))
data$othantiviral2_cmyn <- factor(data$othantiviral2_cmyn, levels = c("1", "0"))
data$othantiviral3_cmyn <- factor(data$othantiviral3_cmyn, levels = c("1", "0"))
data$othantiviral4_cmyn <- factor(data$othantiviral4_cmyn, levels = c("1", "0"))
data$othantiviral5_cmyn <- factor(data$othantiviral5_cmyn, levels = c("1", "0"))
data$antibiotic_cmyn <- factor(data$antibiotic_cmyn, levels = c("1", "2", "3"))
data$antibiotic2_cmyn <- factor(data$antibiotic2_cmyn, levels = c("1", "2", "3"))
data$antibiotic3_cmyn <- factor(data$antibiotic3_cmyn, levels = c("1", "2", "3"))
data$antibiotic4_cmyn <- factor(data$antibiotic4_cmyn, levels = c("1", "2", "3"))
data$antibiotic5_cmyn <- factor(data$antibiotic5_cmyn, levels = c("1", "2", "3"))
data$corticost_cmyn <- factor(data$corticost_cmyn, levels = c("1", "2", "3"))
data$corticost_cmroute <- factor(data$corticost_cmroute, levels = c("1", "2", "3"))
data$antifung_cmyn <- factor(data$antifung_cmyn, levels = c("1", "2", "3"))
data$icu_hoterm <- factor(data$icu_hoterm, levels = c("1", "2", "3"))
data$oxygen_cmoccur <- factor(data$oxygen_cmoccur, levels = c("1", "2", "3"))
data$noninvasive_proccur <- factor(data$noninvasive_proccur, levels = c("1", "2", "3"))
data$invasive_proccur <- factor(data$invasive_proccur, levels = c("1", "2", "3"))
data$pronevent_prtrt <- factor(data$pronevent_prtrt, levels = c("1", "2", "3"))
data$inhalednit_cmtrt <- factor(data$inhalednit_cmtrt, levels = c("1", "2", "3"))
data$tracheo_prtrt <- factor(data$tracheo_prtrt, levels = c("1", "2", "3"))
data$extracorp_prtrt <- factor(data$extracorp_prtrt, levels = c("1", "2", "3"))
data$rrt_prtrt <- factor(data$rrt_prtrt, levels = c("1", "2", "3"))
data$inotrop_cmtrt <- factor(data$inotrop_cmtrt, levels = c("1", "2", "3"))
data$other_cmyn <- factor(data$other_cmyn, levels = c("1", "2", "3"))
data$treatment_complete <- factor(data$treatment_complete, levels = c("0", "1", "2"))
data$vrialpneu_ceoccur <- factor(data$vrialpneu_ceoccur, levels = c("1", "2", "3"))
data$bactpneu_ceoccur <- factor(data$bactpneu_ceoccur, levels = c("1", "2", "3"))
data$ards_ceoccur <- factor(data$ards_ceoccur, levels = c("1", "2", "3"))
data$cryptogenic_ceterm <- factor(data$cryptogenic_ceterm, levels = c("1", "2", "3"))
data$pneumothorax_ceterm <- factor(data$pneumothorax_ceterm, levels = c("1", "2", "3"))
data$pleuraleff_ceterm <- factor(data$pleuraleff_ceterm, levels = c("1", "2", "3"))
data$bronchio_ceterm <- factor(data$bronchio_ceterm, levels = c("1", "2", "3"))
data$meningitis_ceterm <- factor(data$meningitis_ceterm, levels = c("1", "2", "3"))
data$seizure_ceterm <- factor(data$seizure_ceterm, levels = c("1", "2", "3"))
data$stroke_ceterm <- factor(data$stroke_ceterm, levels = c("1", "2", "3"))
data$heartfailure_ceterm <- factor(data$heartfailure_ceterm, levels = c("1", "2", "3"))
data$endocarditis_aeterm <- factor(data$endocarditis_aeterm, levels = c("1", "2", "3"))
data$arrhythmia_ceterm <- factor(data$arrhythmia_ceterm, levels = c("1", "2", "3"))
data$ischaemia_ceterm <- factor(data$ischaemia_ceterm, levels = c("1", "2", "3"))
data$cardiacarrest_ceterm <- factor(data$cardiacarrest_ceterm, levels = c("1", "2", "3"))
data$bacteraemia_ceterm <- factor(data$bacteraemia_ceterm, levels = c("1", "2", "3"))
data$coagulo_ceterm <- factor(data$coagulo_ceterm, levels = c("1", "2", "3"))
data$aneamia_ceterm <- factor(data$aneamia_ceterm, levels = c("1", "2", "3"))
data$rhabdomyolsis_ceterm <- factor(data$rhabdomyolsis_ceterm, levels = c("1", "2", "3"))
data$renalinjury_ceterm <- factor(data$renalinjury_ceterm, levels = c("1", "2", "3"))
data$gastro_ceterm <- factor(data$gastro_ceterm, levels = c("1", "2", "3"))
data$pancreat_ceterm <- factor(data$pancreat_ceterm, levels = c("1", "2", "3"))
data$liverdysfunction_ceterm <- factor(data$liverdysfunction_ceterm, levels = c("1", "2", "3"))
data$hyperglycemia_aeterm <- factor(data$hyperglycemia_aeterm, levels = c("1", "2", "3"))
data$hypoglycemia_ceterm <- factor(data$hypoglycemia_ceterm, levels = c("1", "2", "3"))
data$other_ceoccur <- factor(data$other_ceoccur, levels = c("1", "2", "3"))
data$complications_complete <- factor(data$complications_complete, levels = c("0", "1", "2"))
data$recruitment <- factor(data$recruitment, levels = c("1", "0"))
data$study_2 <- factor(data$study_2, levels = c("1", "0"))
data$study_3 <- factor(data$study_3, levels = c("1", "0"))
data$study_participation_complete <- factor(data$study_participation_complete, levels = c("0", "1", "2"))
data$dsterm <- factor(data$dsterm, levels = c("1", "2", "3", "4", "5", "6"))
data$dsstdtcyn <- factor(data$dsstdtcyn, levels = c("1", "2", "3"))
data$suppds_qval <- factor(data$suppds_qval, levels = c("1", "2", "3", "4"))
data$oxygen_proccur <- factor(data$oxygen_proccur, levels = c("1", "2", "3"))
data$renal_proccur <- factor(data$renal_proccur, levels = c("1", "2", "3"))
data$other_cmoccur <- factor(data$other_cmoccur, levels = c("1", "2", "3"))
data$siteyn <- factor(data$siteyn, levels = c("1", "2", "3"))
data$subjidcat <- factor(data$subjidcat, levels = c("1", "2"))
data$outcome_complete <- factor(data$outcome_complete, levels = c("0", "1", "2"))
data$core_additional_information_complete <- factor(data$core_additional_information_complete, levels = c("0", "1", "2"))


levels(data$redcap_event_name) <- c("Day 1 Hospital Admission (Arm 1: TIER 0)", "Day 3 (Arm 1: TIER 0)", "Day 6 (Arm 1: TIER 0)", "Day 9 (Arm 1: TIER 0)", "Additional days (Arm 1: TIER 0)", "Discharge/Death (Arm 1: TIER 0)", "Day 1 Hospital&ICU Admission (Arm 2: TIER 1)", "Day 3 (Arm 2: TIER 1)", "Day 6 (Arm 2: TIER 1)", "Day 9 (Arm 2: TIER 1)", "Additional days (Arm 2: TIER 1)", "Discharge/Death (Arm 2: TIER 1)", "Day 1 (Arm 3: TIER 2)", "Day 2 (Arm 3: TIER 2)", "Day 3 (Arm 3: TIER 2)", "Day 4 (Arm 3: TIER 2)", "Day 5 (Arm 3: TIER 2)", "Day 6 (Arm 3: TIER 2)", "Day 7 (Arm 3: TIER 2)", "Day 8 (Arm 3: TIER 2)", "Day 9 (Arm 3: TIER 2)", "Day 10 (Arm 3: TIER 2)", "Day 11 (Arm 3: TIER 2)", "Day 12 (Arm 3: TIER 2)", "Day 13 (Arm 3: TIER 2)", "Day 14 (Arm 3: TIER 2)", "Additional days (Arm 3: TIER 2)", "Discharge/Death (Arm 3: TIER 2)")
levels(data$redcap_repeat_instrument) <- c("Pre-admission medication", "Infectious Respiratory Disease Pathogen Testing", "Daily Form")
levels(data$participant_identification_number_pin_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$tiers_faorres___1) <- c("Unchecked", "Checked")
levels(data$tiers_faorres___2) <- c("Unchecked", "Checked")
levels(data$tiers_faorres___3) <- c("Unchecked", "Checked")
levels(data$tiers_consent_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$corona_ieorres) <- c("Yes", "No")
levels(data$coriona_ieorres2) <- c("Yes", "No")
levels(data$fever) <- c("Yes", "No")
levels(data$cough) <- c("Yes", "No")
levels(data$dyspnoe) <- c("Yes", "No")
levels(data$ari) <- c("Yes", "No")
levels(data$symptoms_epi_travel) <- c("YES", "NO", "Unknown")
levels(data$symptoms_epi_physical) <- c("YES", "NO", "Unknown")
levels(data$symptoms_epi_healthfac) <- c("YES", "NO", "Unknown")
levels(data$symptoms_epi_lab) <- c("YES", "NO", "Unknown")
levels(data$symptoms_epi_pathogen) <- c("YES", "NO", "Unknown")
levels(data$symptoms_epi_animal) <- c("YES", "NO", "Unknown")
levels(data$inclusion_criteria_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$sex) <- c("Male", "Female", "Not specified")
levels(data$agedatyn) <- c("Yes", "No")
levels(data$age_estimateyearsu) <- c("Months", "Years")
levels(data$ethnic___1) <- c("Unchecked", "Checked")
levels(data$ethnic___2) <- c("Unchecked", "Checked")
levels(data$ethnic___3) <- c("Unchecked", "Checked")
levels(data$ethnic___4) <- c("Unchecked", "Checked")
levels(data$ethnic___5) <- c("Unchecked", "Checked")
levels(data$ethnic___6) <- c("Unchecked", "Checked")
levels(data$ethnic___7) <- c("Unchecked", "Checked")
levels(data$ethnic___8) <- c("Unchecked", "Checked")
levels(data$ethnic___9) <- c("Unchecked", "Checked")
levels(data$ethnic___10) <- c("Unchecked", "Checked")
levels(data$healthwork_erterm) <- c("YES", "NO", "N/A")
levels(data$labwork_erterm) <- c("YES", "NO", "N/A")
levels(data$pregyn_rptestcd) <- c("YES", "NO", "Unknown", "N/A")
levels(data$postpart_rptestcd) <- c("Yes", "No")
levels(data$pregout_rptestcd) <- c("Live birth", "Still birth")
levels(data$aplb_lbperf) <- c("Yes", "No", "N/A")
levels(data$aplb_lborres) <- c("Positive", "Negative")
levels(data$aplb_lbmethod) <- c("PCR", "Other")
levels(data$apdm_age) <- c("Yes", "No")
levels(data$apvs_weightu) <- c("kg", "lbs")
levels(data$apsc_gestout) <- c("Term birth ( >= 37wk GA)", "Preterm birth (< 37wk GA)", "N/A")
levels(data$apsc_brfedind) <- c("Yes", "No", "N/A")
levels(data$apsc_brfedindy) <- c("Currently breastfed", "Breastfeeding discontinued", "N/A")
levels(data$apsc_dvageind) <- c("Yes", "No", "N/A")
levels(data$apsc_vcageind) <- c("Yes", "No", "Unknown", "N/A")
levels(data$demographics_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$hooccur) <- c("Yes-facility is a study site", "Yes-facility is not a study site", "No", "N/A")
levels(data$subjidcat_transfer) <- c("Same as above", "Different", "N/A")
levels(data$travel_erterm) <- c("Yes", "No", "N/A")
levels(data$supper_trcntry) <- c("Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "The", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cabo Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Republic of the", "Costa Rica", "Cote dIvoire", "Croatia", "Cuba", "Curacao", "Cyprus", "Czechia", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "The", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territories", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe")
levels(data$travel_erterm_2) <- c("Yes", "No", "N/A")
levels(data$supper_trcntry_2) <- c("Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "The", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cabo Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Republic of the", "Costa Rica", "Cote dIvoire", "Croatia", "Cuba", "Curacao", "Cyprus", "Czechia", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "The", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territories", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe")
levels(data$animal_eryn) <- c("Yes", "No", "Unknown", "N/A")
levels(data$animal_eryn_2) <- c("Yes", "No", "Unknown", "N/A")
levels(data$onset_and_admission_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$temp_vsyn) <- c("Yes", "No")
levels(data$temp_vsorresu) <- c("°C", "°F")
levels(data$hr_vsyn) <- c("Yes", "No")
levels(data$rr_vsyn) <- c("Yes", "No")
levels(data$sysbp_vsyn) <- c("Yes", "No")
levels(data$diabp_vsyn) <- c("Yes", "No")
levels(data$dehydration_vsorres) <- c("Yes", "No", "Unknown")
levels(data$stercap_vsyn) <- c("Yes", "No")
levels(data$stercap_vsorres) <- c("Yes", "No", "Unknown")
levels(data$oxy_vsyn) <- c("Yes", "No")
levels(data$oxy_vsorresu) <- c("Room air", "Oxygen therapy", "N/A")
levels(data$fever_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$cough_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$coughsput_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$coughhb_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$sorethroat_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$runnynose_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$earpain_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$wheeze_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$chestpain_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$myalgia_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$jointpain_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$fatigue_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$shortbreath_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$lowerchest_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$headache_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$confusion_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$seizures_cecoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$abdopain_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$vomit_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$diarrhoea_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$conjunct_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$rash_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$skinulcers_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$lymp_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$bleed_ceoccur_v2) <- c("YES", "NO", "Unknown")
levels(data$bleed_ceterm_v2) <- c("YES", "NO", "Unknown")
levels(data$admission_signs_and_symptoms_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$chrincard) <- c("YES", "NO", "Unknown")
levels(data$chronicpul_mhyn) <- c("YES", "NO", "Unknown")
levels(data$asthma_mhyn) <- c("YES", "NO", "Unknown")
levels(data$renal_mhyn) <- c("YES", "NO", "Unknown")
levels(data$modliv) <- c("YES", "NO", "Unknown")
levels(data$mildliver) <- c("YES", "NO", "Unknown")
levels(data$chronicneu_mhyn) <- c("YES", "NO", "Unknown")
levels(data$malignantneo_mhyn) <- c("YES", "NO", "Unknown")
levels(data$chronichaemo_mhyn) <- c("YES", "NO", "Unknown")
levels(data$aidshiv_mhyn) <- c("YES", "NO", "Unknown")
levels(data$obesity_mhyn) <- c("YES", "NO", "Unknown")
levels(data$diabetescom_mhyn) <- c("YES", "NO", "Unknown")
levels(data$diabetes_mhyn) <- c("YES", "NO", "Unknown")
levels(data$rheumatologic_mhyn) <- c("YES", "NO", "Unknown")
levels(data$dementia_mhyn) <- c("YES", "NO", "Unknown")
levels(data$malnutrition_mhyn) <- c("YES", "NO", "Unknown")
levels(data$smoking_mhyn) <- c("Yes", "Never Smoked", "Former Smoker")
levels(data$other_mhyn) <- c("Yes", "No", "Unknown")
levels(data$comorbidities_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$immno_cmtrt) <- c("Yes", "No", "N/A")
levels(data$infect_cmtrt) <- c("Yes", "No", "N/A")
levels(data$preadmission_treatment_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$cmdosfrq) <- c("q.d - once a day", "b.i.d - twice a day", "t.i.d - three times a day", "q.i.d - four times a day", "q.h.s - before bed", "5X a day - five times a day", "q.4h - every four hours", "q.6h - every six hours", "q.o.d - every other day", "prn - as needed", "Other frequency")
levels(data$cmroute) <- c("IV", "oral", "Inhaled", "Unknown", "Other")
levels(data$preadmission_medication_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$daily_hoterm) <- c("Yes", "No", "N/A")
levels(data$daily_fi02_lbyn) <- c("Yes", "No")
levels(data$daily_sa02_lbyn) <- c("Yes", "No")
levels(data$daily_pao2_lbyn) <- c("Yes", "No")
levels(data$daily_pao2_lborresu) <- c("kPa", "mmHg")
levels(data$daily_pao2_lbspec) <- c("Arterial", "Venous", "Capillary", "N/A")
levels(data$daily_pco2_lbyn) <- c("Yes", "No")
levels(data$daily_pco2_lborresu) <- c("kPa", "mmHg")
levels(data$daily_ph_lbyn) <- c("Yes", "No")
levels(data$daily_hco3_lbyn) <- c("Yes", "No")
levels(data$daily_baseex_lbyn) <- c("Yes", "No")
levels(data$avpu_vsorres) <- c("Alert", "Verbal", "Pain", "Unresponsive")
levels(data$daily_gcs_lbyn) <- c("Yes", "No")
levels(data$systolic_vsyn) <- c("Yes", "No")
levels(data$diastolic_vsyn) <- c("Yes", "No")
levels(data$daily_meanart_lbyn) <- c("Yes", "No")
levels(data$daily_urine_lbyn) <- c("Yes", "Estimated", "No")
levels(data$daily_noninvasive_prtrt) <- c("YES", "NO", "N/A")
levels(data$daily_invasive_prtrt) <- c("YES", "NO", "N/A")
levels(data$daily_nasaloxy_cmtrt) <- c("YES", "NO", "N/A")
levels(data$daily_ecmo_prtrt) <- c("YES", "NO", "N/A")
levels(data$daily_rrt_cmtrt) <- c("YES", "NO", "N/A")
levels(data$daily_inotrope_cmyn) <- c("YES", "NO", "N/A")
levels(data$daily_dopless5_cmtrt) <- c("YES", "NO", "N/A")
levels(data$daily_dop5to15_cmtrt) <- c("YES", "NO", "N/A")
levels(data$daily_dopgr15_cmtrt) <- c("YES", "NO", "N/A")
levels(data$daily_neuro_cmtrt) <- c("YES", "NO", "N/A")
levels(data$daily_nitritc_cmtrt) <- c("YES", "NO", "N/A")
levels(data$daily_prone_cmtrt) <- c("YES", "NO", "N/A")
levels(data$daily_trach_prperf) <- c("YES", "NO", "N/A")
levels(data$daily_prperf) <- c("YES", "NO", "N/A")
levels(data$daily_lbperf) <- c("Yes", "No")
levels(data$daily_hb_lbyn) <- c("Yes", "No")
levels(data$daily_hb_lborresu) <- c("g/L", "g/dL")
levels(data$daily_wbc_lbyn) <- c("Yes", "No")
levels(data$daily_wbc_lborresu) <- c("x 10^9 / L", "x 103/µL")
levels(data$daily_lymp_lbyn) <- c("Yes", "No")
levels(data$daily_neutro_lbyn) <- c("Yes", "No")
levels(data$daily_haematocrit_lbyn) <- c("Yes", "No")
levels(data$daily_plt_lbyn) <- c("Yes", "No")
levels(data$daily_plt_lborresu) <- c("x 10^9 / L", "x 103/μL")
levels(data$daily_aptt_lbyn) <- c("Yes", "No")
levels(data$daily_pt_inr_lbyn) <- c("PT done", "INR done", "PT or INR not done")
levels(data$daily_alt_lbyn) <- c("Yes", "No")
levels(data$daily_bil_lbyn) <- c("Yes", "No")
levels(data$daily_bil_lborresu) <- c("µmol/L", "mg/dL")
levels(data$daily_ast_lbyn) <- c("Yes", "No")
levels(data$daily_glucose_lbyn) <- c("Yes", "No")
levels(data$daily_glucose_lborresu) <- c("mmol/L", "mg/dL")
levels(data$daily_bun_lbyn) <- c("Yes", "No")
levels(data$daily_bun_lborresu) <- c("mmol/L", "mg/dL")
levels(data$daily_lactate_lbyn) <- c("Yes", "No")
levels(data$daily_lactate_lborresu) <- c("mmol/L", "mg/dL")
levels(data$daily_ldh_lbyn) <- c("Yes", "No")
levels(data$daily_cpk_lby) <- c("Yes", "No")
levels(data$daily_creat_lbyn) <- c("Yes", "No")
levels(data$daily_creat_lborresu) <- c("μmol/L", "mg/dL", "umol/L")
levels(data$daily_sodium_lbyn) <- c("Yes", "No")
levels(data$daily_potassium_lbyn) <- c("Yes", "No")
levels(data$daily_procal_lbyn) <- c("Yes", "No")
levels(data$daily_crp_lbyn) <- c("Yes", "No")
levels(data$xray_prperf) <- c("YES", "NO", "N/A")
levels(data$infiltrates_faorres) <- c("YES", "NO", "N/A")
levels(data$daily_form_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$mbperf) <- c("YES", "NO", "N/A")
levels(data$influ_mbyn) <- c("YES - Confirmed", "YES - Probable", "NO")
levels(data$influ_mbcat) <- c("A/H3N2", "A/H1N1pdm09", "A/H7N9", "A/H5N1", "A - not typed", "B", "Other")
levels(data$corna_mbcat) <- c("YES - Confirmed", "YES - Probable", "NO")
levels(data$corna_mbcaty) <- c("MERS-CoV", "2019nCoV", "Other CoV")
levels(data$rsv_mbcat) <- c("YES - Confirmed", "YES - Probable", "NO")
levels(data$adeno_mbcat) <- c("YES - Confirmed", "YES - Probable", "NO")
levels(data$bact_mborres) <- c("YES-Confirmed", "NO")
levels(data$other_mbyn) <- c("YES - Confirmed", "YES - Probable", "NO")
levels(data$clinicalpneu_mborres) <- c("YES", "NO", "Unknown")
levels(data$infectuk_mborres) <- c("Yes", "N/A")
levels(data$infectious_respiratory_disease_pathogen_diagnosis_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$daily_mbperf) <- c("Yes", "No")
levels(data$mbspec) <- c("Nasal / NP swab", "Throat swab", "Combined nasal / NP + throat swab", "Sputum", "Bronchoalveolar Lavage (BAL)", "Exotoxin A (ETA)", "CSF", "SAM", "Urine", "Feces / rectal swab", "Blood serum", "Blood EDTA", "Blood RNA", "Other")
levels(data$mbmethod) <- c("PCR", "Culture", "Other")
levels(data$mborres) <- c("Positive", "Negative", "N/A")
levels(data$infectious_respiratory_disease_pathogen_testing_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$antiviral_cmyn) <- c("Yes", "No", "N/A")
levels(data$antiviral_cmtrt___1) <- c("Unchecked", "Checked")
levels(data$antiviral_cmtrt___2) <- c("Unchecked", "Checked")
levels(data$antiviral_cmtrt___3) <- c("Unchecked", "Checked")
levels(data$antiviral_cmtrt___4) <- c("Unchecked", "Checked")
levels(data$antiviral_cmtrt___5) <- c("Unchecked", "Checked")
levels(data$antiviral_cmtrt___6) <- c("Unchecked", "Checked")
levels(data$othantiviral2_cmyn) <- c("Yes", "No")
levels(data$othantiviral3_cmyn) <- c("Yes", "No")
levels(data$othantiviral4_cmyn) <- c("Yes", "No")
levels(data$othantiviral5_cmyn) <- c("Yes", "No")
levels(data$antibiotic_cmyn) <- c("Yes", "No", "N/A")
levels(data$antibiotic2_cmyn) <- c("Yes", "No", "N/A")
levels(data$antibiotic3_cmyn) <- c("Yes", "No", "N/A")
levels(data$antibiotic4_cmyn) <- c("Yes", "No", "N/A")
levels(data$antibiotic5_cmyn) <- c("Yes", "No", "N/A")
levels(data$corticost_cmyn) <- c("Yes", "No", "N/A")
levels(data$corticost_cmroute) <- c("Oral", "Intravenous", "Inhaled")
levels(data$antifung_cmyn) <- c("Yes", "No", "N/A")
levels(data$icu_hoterm) <- c("Yes", "No", "N/A")
levels(data$oxygen_cmoccur) <- c("YES", "NO", "N/A")
levels(data$noninvasive_proccur) <- c("YES", "NO", "N/A")
levels(data$invasive_proccur) <- c("YES", "NO", "N/A")
levels(data$pronevent_prtrt) <- c("YES", "NO", "N/A")
levels(data$inhalednit_cmtrt) <- c("YES", "NO", "N/A")
levels(data$tracheo_prtrt) <- c("YES", "NO", "N/A")
levels(data$extracorp_prtrt) <- c("YES", "NO", "N/A")
levels(data$rrt_prtrt) <- c("YES", "NO", "N/A")
levels(data$inotrop_cmtrt) <- c("YES", "NO", "N/A")
levels(data$other_cmyn) <- c("YES", "NO", "N/A")
levels(data$treatment_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$vrialpneu_ceoccur) <- c("YES", "NO", "N/A")
levels(data$bactpneu_ceoccur) <- c("YES", "NO", "N/A")
levels(data$ards_ceoccur) <- c("YES", "NO", "N/A")
levels(data$cryptogenic_ceterm) <- c("YES", "NO", "N/A")
levels(data$pneumothorax_ceterm) <- c("YES", "NO", "N/A")
levels(data$pleuraleff_ceterm) <- c("YES", "NO", "N/A")
levels(data$bronchio_ceterm) <- c("YES", "NO", "N/A")
levels(data$meningitis_ceterm) <- c("YES", "NO", "N/A")
levels(data$seizure_ceterm) <- c("YES", "NO", "N/A")
levels(data$stroke_ceterm) <- c("YES", "NO", "N/A")
levels(data$heartfailure_ceterm) <- c("YES", "NO", "N/A")
levels(data$endocarditis_aeterm) <- c("YES", "NO", "N/A")
levels(data$arrhythmia_ceterm) <- c("YES", "NO", "N/A")
levels(data$ischaemia_ceterm) <- c("YES", "NO", "N/A")
levels(data$cardiacarrest_ceterm) <- c("YES", "NO", "N/A")
levels(data$bacteraemia_ceterm) <- c("YES", "NO", "N/A")
levels(data$coagulo_ceterm) <- c("YES", "NO", "N/A")
levels(data$aneamia_ceterm) <- c("YES", "NO", "N/A")
levels(data$rhabdomyolsis_ceterm) <- c("YES", "NO", "N/A")
levels(data$renalinjury_ceterm) <- c("YES", "NO", "N/A")
levels(data$gastro_ceterm) <- c("YES", "NO", "N/A")
levels(data$pancreat_ceterm) <- c("YES", "NO", "N/A")
levels(data$liverdysfunction_ceterm) <- c("YES", "NO", "N/A")
levels(data$hyperglycemia_aeterm) <- c("YES", "NO", "N/A")
levels(data$hypoglycemia_ceterm) <- c("YES", "NO", "N/A")
levels(data$other_ceoccur) <- c("YES", "NO", "N/A")
levels(data$complications_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$recruitment) <- c("Yes", "No")
levels(data$study_2) <- c("Yes", "No")
levels(data$study_3) <- c("Yes", "No")
levels(data$study_participation_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$dsterm) <- c("Discharged alive", "Hospitalization", "Transfer to other facility", "Death", "Palliative discharge", "Unknown")
levels(data$dsstdtcyn) <- c("Yes", "No", "N/A")
levels(data$suppds_qval) <- c("Same as before illness", "Worse", "Better", "N/A")
levels(data$oxygen_proccur) <- c("YES", "NO", "N/A")
levels(data$renal_proccur) <- c("YES", "NO", "N/A")
levels(data$other_cmoccur) <- c("YES", "NO", "N/A")
levels(data$siteyn) <- c("Yes", "No", "N/A")
levels(data$subjidcat) <- c("Same as the above", "Different")
levels(data$outcome_complete) <- c("Incomplete", "Unverified", "Complete")
levels(data$core_additional_information_complete) <- c("Incomplete", "Unverified", "Complete")
